// FrontPage/pc/ss/da/src/page/component/footer.jsx
import React, { Component } from "react";
import "./common.scss";
export default class Footer extends Component {
    render() {
        return (
            <div className="footer">
                <p><span>Copyright Jusfoun.com © 2016-2017</span><span>华坪县尚农农业科技开发投资有限责任公司</span></p>
                <p><span>技术支持</span> 丽江市旅游大数据产业有限责任公司</p>
            </div>
        )
    }
}

// FrontPage/pc/ss/syxf/src/components/footer.vue
<template>
  <div class="footer">
     <p>Copyright Jusfoun.com © 2016-2017 &nbsp;&nbsp;华坪县尚农农业科技开发投资有限责任公司 &nbsp;&nbsp; 京ICP备12012279号-18</p>
     <p>技术支持 丽江市旅游大数据产业有限责任公司</p>
  </div>
</template>

<script>

export default {
  name: 'Footer'
}
</script>

<style scoped lang="scss">
.footer {
    text-align: center;
    color: rgb(119, 119, 119);
    font-size: 12px;
    height: 80px;
    box-sizing: border-box;
    line-height: 18px;
    bottom: 0px;
    width: 100%;
    min-width: 1280px;
    background: rgb(247, 247, 247);
    padding: 20px 0px;
}
</style>
